# 配置数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT
#    配置springboot为开发环境
  profiles:
    active: dev
# 配置mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名匹配
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL打印日志
  global-config:
    db-config:
      id-type: id_worker # 配置全局主键策略
      # 配置逻辑删除
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 配置springboot为开发环境